from Mod.OriginalPackage import Unit
from Mod.OriginalPackage import Skill
from ExternalLibrary.ExternalLibrary import RegistrationCard

RegistrationCard(
    *5 * [Unit.Wolf()],
    *5 * [Unit.ImperialSoldier()],
    *5 * [Unit.Goblin()],
    *3 * [Unit.Ghoul()],
    *3 * [Unit.ImperialKnight()],
    *2 * [Unit.Doppler()],
    *2 * [Unit.GiantGhoul()],
    *2 * [Unit.OneEyedGhoul()],
    Unit.LittlePudding(),
    *3 * [Unit.Spirit()],
    Unit.DobbyGolem(),
    *2 * [Unit.BigWolf()],
    Unit.GoblinKing(),
    *4 * [Unit.ImperialShotter()],
    Unit.PiterJerLfu(),
    Unit.Blueness(),
    Unit.K_902(),
    Unit.BathFirePhoenix(),
    *2 * [Unit.LowerOrderVampire()],
    Unit.HighPriestofAltoMadike(),
    Unit.Irinas(),
    Unit.RabbitWart(),
    *4 * [Unit.Aetherial()],
    Unit.Harwick(),
    *4 * [Unit.SkeletonSoldier()],
    *3 * [Unit.SkeletalMage()],
    *4 * [Unit.Ghosts()],
    *2 * [Unit.MotherofGhosts()],
    *3 * [Unit.MagicSource()],
    *2 * [Unit.GlassGiant()],
    *2 * [Unit.StoneGiant()],
    *2 * [Unit.SnowGiant()],
    *2 * [Unit.Mandrake()],
    Unit.Bell(),
    *2 * [Unit.SkeletonGiant()],
    Unit.Evilest(),
    *4 * [Unit.Worm()],
    *3 * [Unit.GiantMalu()],
    *4 * [Unit.Ants()],
    *2 * [Unit.WormDragon()],      
    *3 * [Unit.DamascusButterfly()],
    Unit.Leviathan(),
    Unit.CPrimePlus(),
    *2 * [Unit.DemonJay()],
    Unit.Bahamut(),
    *2 * [Unit.GoblinThief()],
    Unit.B_971(),
    Unit.C_999(),
    Unit.WuZun(),
    *3 * [Unit.Deeren()],
    *3 * [Unit.Elfslave()],
    *3 * [Unit.GiantGoblin()],
    Unit.Flanders(),
    Unit.Deusexmachina(),
    Unit.DeadSage(),
    *3 * [Unit.ChaosEvil()],
    Unit.TheDomeofSky(),
    *3 * [Unit.MoonbearclassAerialBattleship()],

    *1 * [Skill.Explosion()],
    *2 * [Skill.BodyWeak()],
    Skill.SoulFusion(),
    *2 * [Skill.WarSupplies()],
    *3 * [Skill.HolyBlessing()],
    Skill.NoSunStone(),
    *3 * [Skill.LightningStrike()],
    Skill.TheFinalBattle(),
    *4 * [Skill.MagicArrow()],
    *3 * [Skill.MagicMissile()],
    Skill.DieImmediately(),
    *2 * [Skill.Coin()],
    *2 * [Skill.ReligiousTrial()],
    Skill.ChaosFactor(),
    Skill.GreatPatrioticWar(),
    Skill.RustyAxe(),
    *4 * [Skill.FireBoom()],
    *3 * [Skill.LionHeart()],
    *3 * [Skill.Oppression()],
    *2 * [Skill.MagicBlasting()],
    Skill.InfiniteSacrifice(),
    *2 * [Skill.LuckyCoin()],
    *2 * [Skill.Healing()],
    *3 * [Skill.ImaginaryParticleMissile()],
    *3 * [Skill.NanoTomographyProtection()],
    *3 * [Skill.MagicShield()],
    *3 * [Skill.DivineRefuge()],
    *2 * [Skill.BodyDeprivation()],
    *3 * [Skill.StoneBound()],
    *3 * [Skill.ShieldBacklash()],
    *4 * [Skill.Curse()],
    *2 * [Skill.CurseWaveTorrent()],
    *2 * [Skill.TheFlameofBoredom()],
    *2 * [Skill.BlackMistofDead()],
    *4 * [Skill.GuardianWideArea()],
)
